trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AzureFlaskConnection'  # Replace if your service connection has a different name
  appName: 'AI-Arcade'                       # Your Azure App Service name
  packageDir: '$(Build.ArtifactStagingDirectory)/package'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13'
    addToPath: true

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(packageDir)/flaskapp.zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(packageDir)/flaskapp.zip'
